language: ruby
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
before_install: gem install bundler -v 2.0.1 --no-document
before_script:
  - bundle exec appraisal install --jobs=3
script:
  - bundle exec rubocop
  - bundle exec appraisal rspec
